print:
  image: ubuntu
  script: echo "saya sedang belajar github-ci"

variables:
  CI_REGISTRY_USER: "admin"
  CI_REGISTRY_PASSWORD: "nutanix/4u"
  CI_DEPENDENCY_PROXY_SERVER: "10.42.29.110:5000"

build:docker:
  stage: build
  image: docker:stable
  service:
    - name: docker:18.09-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry=10.42.29.110:5000"]
      alias: dockerd
  variables:
    DOCKER_HOST: tcp://dockerd:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER
  script:
    - docker build -f Dockerfile -t $CI_DEPENDENCY_PROXY_SERVER/vitriagrn/bootcamp-nginx:latest .
    - docker push $CI_DEPENDENCY_PROXY_SERVER/vitriagrn/bootcamp-nginx:latest
